name: api
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  #https://pub.dev/packages/shelf
  shelf: ^1.3.0
  #https://pub.dev/packages/shelf_router
  shelf_router: ^1.1.2
  #https://pub.dev/packages/shelf_router_generator
  shelf_router_generator: ^1.0.2

dev_dependencies:
  lints: ^1.0.0
